server:
  port: 8888

spring:
  application:
    name: spring-config-server
  profiles: 
    active: 
    - git
#    - native

# Actuator
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - refresh
        - restart
        - beans

---
# Git Config 
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KIM-JONG-YOUNG/spring-config-service
          search-paths: ./configs                                               # Folder 경로 
          default-label: master                                                # Branch 정보
          delete-untracked-branches: true                           # Remote Repository만 사용
          
--- 
# Local Config
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          # Folder 경로 
          search-locations: file:./configs
