spring:

  # MariaDB
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://mariadb:3306/board
      username: root
      password: root
      maximum-pool-size: 10
      connection-test-query: SELECT 1

  # JPA
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true